image: Visual Studio 2017
configuration: Release
version: '1.0.{build}'

dotnet_csproj:
    patch: true
    file: src\GraphQl.Extensions\GraphQl.Extensions.csproj
    version: '{version}'
    
before_build:
- cmd: >-
    dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test_script:
  - cmd: dotnet test tests\GraphQl.Extensions.Tests\GraphQl.Extensions.Tests.csproj

deploy:
  provider: NuGet
  api_key:
    secure: rdQj1p4P/h/Gpa8wLLrop6rLzzoBWGqMR2CV/viIq/r+LKRS2boB/wV+lqITrbBR
  skip_symbols: true
  artifact: /.*\.nupkg/